"use strict";

const LIBPAT_DIR = __dirname + '/../../libpat';

const LIBPAT_NODEPAT_DIR = __dirname + '/../src/libpat';
const LIBPAT_NODEPAT_BUILD_DIR = LIBPAT_NODEPAT_DIR + '/build';
const LIBPAT_NODEPAT_CMAKE_DEBUG_DIR = LIBPAT_NODEPAT_DIR + '/cmake-build-debug';
const LIBPAT_NODEPAT_CMAKE_RELEASE_DIR = LIBPAT_NODEPAT_DIR + '/cmake-build-release';
const LIBPAT_NODEPAT_IDEA_DIR = LIBPAT_NODEPAT_DIR + '/.idea';
const LIBPAT_NODEPAT_PAT_PLAY_DIR = LIBPAT_NODEPAT_DIR + '/patplay';
const LIBPAT_NODEPAT_GITKEEP_FILE = LIBPAT_NODEPAT_BUILD_DIR + '/.gitkeep';

module.exports.LIBPAT_DIR = LIBPAT_DIR;
module.exports.LIBPAT_NODEPAT_BUILD_DIR = LIBPAT_NODEPAT_BUILD_DIR;
module.exports.LIBPAT_NODEPAT_DIR = LIBPAT_NODEPAT_DIR;
module.exports.LIBPAT_NODEPAT_CMAKE_DEBUG_DIR = LIBPAT_NODEPAT_CMAKE_DEBUG_DIR;
module.exports.LIBPAT_NODEPAT_CMAKE_RELEASE_DIR = LIBPAT_NODEPAT_CMAKE_RELEASE_DIR;
module.exports.LIBPAT_NODEPAT_IDEA_DIR = LIBPAT_NODEPAT_IDEA_DIR;
module.exports.LIBPAT_NODEPAT_PAT_PLAY_DIR = LIBPAT_NODEPAT_PAT_PLAY_DIR;
module.exports.LIBPAT_NODEPAT_GITKEEP_FILE = LIBPAT_NODEPAT_GITKEEP_FILE;
