name: PAT CI/CD

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Enable Symlinks (Windows)
        run: git config core.symlinks true
        if: matrix.os == 'windows-latest'

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      
      - name: Install Dependencies (Linux)
        run: sudo apt-get install libavutil-dev libswresample-dev libavdevice-dev libavcodec-dev libavformat-dev libswscale-dev libsdl2-dev pulseaudio pavucontrol
        if: matrix.os == 'ubuntu-latest'

      - name: Configure PulseAudio (Linux)
        run: |
          pulseaudio --daemonize --exit-idle-time=-1
          pacmd load-module module-null-sink sink_name=AudioOut
        if: matrix.os == 'ubuntu-latest'

      - name: Install Dependencies (Mac OS)
        run: |
          brew cask install blackhole
          brew install ffmpeg pkg-config sdl2
        if: matrix.os == 'macos-latest'
      
      - name: Install Dependencies (Windows)
        run: |
          Function InstallWebZip($URL, $FolderName) {
            Invoke-WebRequest $URL -OutFile "${FolderName}.zip"
            Expand-Archive -Path "${FolderName}.zip" -DestinationPath "${FolderName}"
            Move-Item -Path ".\${FolderName}\*\*" -Destination ".\${FolderName}"
          }

          InstallWebZip https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-4.2.2-win64-dev.zip "ffmpeg"
          InstallWebZip https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip "sdl2"

          $currentLocation =(Get-Location).toString()
          $ffmpegRoot = "$currentLocation\ffmpeg"
          $sdl2Root = "$currentLocation\sdl2"
          $env:GYP_DEFINES = "ffmpeg-root=`"${ffmpegRoot}`" sdl2-root=`"${sdl2Root}`""
          $env:INCLUDE = "$ffmpegRoot\include;$sdl2Root\include"
          $env:LIB = "$ffmpegRoot\lib;$sdl2Root\lib\x64"
        if: matrix.os == 'windows-latest'

      - name: Build nodepat
        working-directory: nodepat
        run: |
          npm i -g npm
          npm i
          npm run build
          npm test

      - name: Build pypat
        working-directory: pypat
        run: |
          pip install pytest
          python setup.py build_ext --inplace
          python setup.py build
          python -m pytest
