name: PAT CI/CD

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      
      - name: Install Dependencies (Linux)
        run: sudo apt-get install libavutil-dev libswresample-dev libavdevice-dev libavcodec-dev libavformat-dev libswscale-dev libsdl2-dev pulseaudio pavucontrol
        if: matrix.os == 'ubuntu-latest'

      - name: Configure PulseAudio (Linux)
        run: |
          pulseaudio --daemonize --exit-idle-time=-1
          pacmd load-module module-null-sink sink_name=AudioOut
        if: matrix.os == 'ubuntu-latest'

      - name: Install Dependencies (Mac OS)
        run: |
          brew cask install blackhole
          brew install ffmpeg pkg-config sdl2
        if: matrix.os == 'macos-latest'

      - name: Build nodepat
        working-directory: nodepat
        run: |
          npm i -g npm
          npm i
          npm run build
          npm test

      - name: Build pypat
        working-directory: pypat
        run: |
          pip install pytest
          python setup.py build_ext --inplace
          python -m pytest
